ai:
  default: ai
display_label_popup: true
epsilon: 10.0
file_dock:
  closable: false
  floatable: true
  movable: true
  show: true
file_search: null
keep_prev: false
logger_level: info
login:
  username:
  - admin
  - dd
store_data: true
